
help:
	@echo usage: make update

update:
	mv -f ethercodes.dat ethercodes.dat.bak || true
	wget -O oui.txt http://standards.ieee.org/regauth/oui/oui.txt
	perl ./ouitxt_convert.pl oui.txt | sort > ethercodes.dat || true
	diff -au ethercodes.dat.bak ethercodes.dat || true
